import { StarterFile, StarterGenerationOptions } from "../types";
import { formatModelDisplaySize } from "../../memory-calculator";

export function generateAgentStarter(options: StarterGenerationOptions): StarterFile[] {
  const { model, explanation } = options;
  const projectName = `hack-day-starter-agent-${model.family}`;
  const displaySize = formatModelDisplaySize(model);
  const contextK = (model.contextTokens / 1024).toFixed(0);

  const capabilitiesList = [
    model.capabilities.tools === true ? "Tools (Verified)" : null,
    model.capabilities.vision === true ? "Vision" : null,
    model.capabilities.thinking === true ? "Thinking" : null,
  ]
    .filter(Boolean)
    .join(", ");

  const whyThisModel =
    explanation ||
    `${model.displayName} was selected for its verified native tool-calling capabilities and excellent fit for autonomous agentic workflows on your hardware.`;

  // 1. README.md
  const readmeContent = `# ${projectName}

Generated by **Hack Day Starter**

A lightweight TypeScript tool-calling agent demonstrating a **real autonomous execution loop** with local Ollama models.

---

## Selected Model

- **Model:** ${model.displayName}
- **Provider:** ${model.provider}
- **Ollama tag:** \`${model.ollamaTag}\`
- **${model.exactManifestSizeBytes !== null ? "Manifest size" : "Ollama listed size"}:** ${displaySize}
- **Context Window:** ${contextK}k tokens (${model.contextTokens.toLocaleString()})
- **Tool Calling:** Verified native function calling support
- **Quantization:** \`${model.quantization}\`
- **License:** ${model.license}
- **Capabilities:** ${capabilitiesList}
- **Primary Source:** [${model.ollamaUrl}](${model.ollamaUrl})

---

## Tool-Calling Loop Architecture

This starter implements a genuine, non-faked tool-calling loop:

\`\`\`text
User Question
      │
      ▼
Local Ollama API (/api/chat) ──[tools defined]──► Model analyzes intent
                                                         │
                                    ┌────────────────────┴────────────────────┐
                                    ▼                                         ▼
                            Model returns tool_call                    Direct text response
                                    │                                         │
                                    ▼                                         ▼
                           Execute tool locally                            Display
                                    │
                                    ▼
                         Append { role: 'tool' }
                                    │
                                    ▼
                     Send back to Ollama (/api/chat)
                                    │
                                    ▼
                           Final agent response
\`\`\`

---

## Setup

Run the following commands in your terminal:

\`\`\`bash
# 1. Pull the verified model with native tool-calling support
ollama pull ${model.ollamaTag}

# 2. Install project dev dependencies
npm install

# 3. Run the interactive tool-calling agent
npm run dev
\`\`\`

---

## Why this model

${whyThisModel}

---

## How to add custom tools

1. Create your tool definition in \`src/tools/\` (see \`src/tools/calculator.ts\` as a reference).
2. Define the JSON schema in the tool definition:
   \`\`\`typescript
   export const myTool: ToolDefinition = {
     type: "function",
     function: {
       name: "fetch_weather",
       description: "Get current weather for a city",
       parameters: {
         type: "object",
         properties: {
           city: { type: "string", description: "City name" }
         },
         required: ["city"]
       }
     }
   };
   \`\`\`
3. Register the tool in \`src/index.ts\` in the \`AVAILABLE_TOOLS\` map.

---

## How to change the model

Make sure the target model supports native tool calling before switching:

1. **Environment variable:**
   \`\`\`bash
   OLLAMA_MODEL="<other-model-with-tools:tag>" npm run dev
   \`\`\`
2. **Or editing \`src/index.ts\`**:
   \`\`\`typescript
   const MODEL_TAG = process.env.OLLAMA_MODEL || "${model.ollamaTag}";
   \`\`\`
`;

  // 2. package.json
  const packageJsonContent = JSON.stringify(
    {
      name: projectName,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        dev: "tsx src/index.ts",
        build: "tsc",
        start: "node dist/index.js",
      },
      devDependencies: {
        "@types/node": "^20.11.0",
        tsx: "^4.7.0",
        typescript: "^5.3.3",
      },
    },
    null,
    2
  ) + "\n";

  // 3. tsconfig.json
  const tsconfigContent = JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        esModuleInterop: true,
        strict: true,
        skipLibCheck: true,
        outDir: "./dist",
        rootDir: "./src",
      },
      include: ["src/**/*"],
    },
    null,
    2
  ) + "\n";

  // 4. .gitignore
  const gitignoreContent = `node_modules/
dist/
.env
.DS_Store
*.log
`;

  // 5. src/tools/calculator.ts
  const calculatorToolContent = `/**
 * Calculator Tool Definition and Safe Arithmetic Evaluator.
 * Safe execution without eval or code generation.
 */

export interface ToolDefinition {
  type: "function";
  function: {
    name: string;
    description: string;
    parameters: {
      type: "object";
      properties: Record<string, { type: string; description: string }>;
      required: string[];
    };
  };
}

export const calculatorTool: ToolDefinition = {
  type: "function",
  function: {
    name: "calculate",
    description:
      "Evaluates a mathematical arithmetic expression and returns the numeric result. Supports +, -, *, /, %, ^, and parentheses.",
    parameters: {
      type: "object",
      properties: {
        expression: {
          type: "string",
          description:
            "The mathematical expression to evaluate, e.g. '142 * 38', '(120 + 45) / 5', or '2 ^ 10'.",
        },
      },
      required: ["expression"],
    },
  },
};

/**
 * Safely evaluates arithmetic expressions using a recursive descent parser.
 */
export function executeCalculator(args: { expression: string }): string {
  const expr = args?.expression;
  if (!expr || typeof expr !== "string") {
    return "Error: Missing expression argument.";
  }

  try {
    const sanitized = expr.replace(/\\s+/g, "");
    // Validate characters: only numbers, operators, parens, and decimal points
    if (!/^[0-9+\\-*/%^().]+$/.test(sanitized)) {
      return \`Error: Invalid characters in mathematical expression '\${expr}'.\`;
    }

    const result = evaluateExpression(sanitized);
    if (!isFinite(result) || isNaN(result)) {
      return \`Error: Calculation produced invalid number (\${result}).\`;
    }
    return String(result);
  } catch (err: any) {
    return \`Error evaluating '\${expr}': \${err.message || "Invalid syntax"}\`;
  }
}

// ---------------------------------------------------------------------------
// Safe Math Expression Parser (no eval)
// ---------------------------------------------------------------------------

function evaluateExpression(str: string): number {
  let pos = 0;

  function peek(): string {
    return str[pos] || "";
  }

  function get(): string {
    return str[pos++] || "";
  }

  function parseNumber(): number {
    const start = pos;
    if (peek() === "-") get();
    while (/[0-9.]/.test(peek())) get();
    const token = str.slice(start, pos);
    const num = parseFloat(token);
    if (isNaN(num)) throw new Error(\`Invalid number at '\${token}'\`);
    return num;
  }

  function parseFactor(): number {
    if (peek() === "(") {
      get(); // consume '('
      const result = parseAddSub();
      if (peek() !== ")") throw new Error("Missing closing parenthesis");
      get(); // consume ')'
      return result;
    }
    return parseNumber();
  }

  function parseExponent(): number {
    let left = parseFactor();
    while (peek() === "^") {
      get(); // consume '^'
      const right = parseFactor();
      left = Math.pow(left, right);
    }
    return left;
  }

  function parseMulDiv(): number {
    let left = parseExponent();
    while (peek() === "*" || peek() === "/" || peek() === "%") {
      const op = get();
      const right = parseExponent();
      if (op === "*") left *= right;
      else if (op === "/") {
        if (right === 0) throw new Error("Division by zero");
        left /= right;
      } else if (op === "%") {
        left %= right;
      }
    }
    return left;
  }

  function parseAddSub(): number {
    let left = parseMulDiv();
    while (peek() === "+" || peek() === "-") {
      const op = get();
      const right = parseMulDiv();
      if (op === "+") left += right;
      else if (op === "-") left -= right;
    }
    return left;
  }

  const value = parseAddSub();
  if (pos < str.length) {
    throw new Error(\`Unexpected token '\${str[pos]}' at position \${pos}\`);
  }
  return value;
}
`;

  // 6. src/ollama.ts
  const ollamaClientContent = `/**
 * Direct client for local Ollama API with Native Tool-Calling Support.
 * Uses native Node.js fetch (no external SDK dependencies required).
 */

import { ToolDefinition } from "./tools/calculator.js";

export interface ToolCall {
  function: {
    name: string;
    arguments: Record<string, any>;
  };
}

export interface ChatMessage {
  role: "system" | "user" | "assistant" | "tool";
  content: string;
  tool_calls?: ToolCall[];
}

export interface OllamaChatResponse {
  model: string;
  created_at: string;
  message: ChatMessage;
  done: boolean;
  total_duration?: number;
  load_duration?: number;
  prompt_eval_count?: number;
  eval_count?: number;
}

export class OllamaAgentClient {
  private readonly baseUrl: string;
  public readonly modelTag: string;

  constructor(modelTag: string, baseUrl = "http://localhost:11434") {
    this.modelTag = modelTag;
    this.baseUrl = baseUrl.replace(/\\/$/, "");
  }

  /**
   * Checks if the local Ollama instance is accessible.
   */
  async checkConnection(): Promise<boolean> {
    try {
      const res = await fetch(\`\${this.baseUrl}/api/tags\`, { method: "GET" });
      return res.ok;
    } catch {
      return false;
    }
  }

  /**
   * Checks if the configured model is installed locally.
   */
  async isModelInstalled(): Promise<boolean> {
    try {
      const res = await fetch(\`\${this.baseUrl}/api/tags\`, { method: "GET" });
      if (!res.ok) return false;
      const data = (await res.json()) as { models?: Array<{ name: string }> };
      const normalizedTag = this.modelTag.includes(":")
        ? this.modelTag
        : \`\${this.modelTag}:latest\`;
      return (
        data.models?.some(
          (m) => m.name === this.modelTag || m.name === normalizedTag
        ) ?? false
      );
    } catch {
      return false;
    }
  }

  /**
   * Calls Ollama /api/chat with tools enabled.
   */
  async chatWithTools(
    messages: ChatMessage[],
    tools?: ToolDefinition[]
  ): Promise<ChatMessage> {
    const payload: Record<string, any> = {
      model: this.modelTag,
      messages,
      stream: false,
    };

    if (tools && tools.length > 0) {
      payload.tools = tools;
    }

    const res = await fetch(\`\${this.baseUrl}/api/chat\`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });

    if (!res.ok) {
      const errorText = await res.text().catch(() => res.statusText);
      throw new Error(\`Ollama API error (\${res.status}): \${errorText}\`);
    }

    const data = (await res.json()) as OllamaChatResponse;
    return data.message;
  }
}
`;

  // 7. src/index.ts
  const indexContent = `import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { OllamaAgentClient, ChatMessage } from "./ollama.js";
import { calculatorTool, executeCalculator } from "./tools/calculator.js";

// Configured model tag: verified for native tool calling
const MODEL_TAG = process.env.OLLAMA_MODEL || "${model.ollamaTag}";
const OLLAMA_HOST = process.env.OLLAMA_HOST || "http://localhost:11434";

// Register available agent tools
const TOOLS = [calculatorTool];
const TOOL_HANDLERS: Record<string, (args: any) => string> = {
  calculate: executeCalculator,
};

const SYSTEM_PROMPT = \`You are an accurate, helpful autonomous assistant with access to local tools.
When asked to perform arithmetic or mathematical operations, you MUST call the 'calculate' tool rather than guessing mental math.
When receiving a tool result, synthesize it into a clear, concise final answer.\`;

async function main() {
  console.log("=================================================");
  console.log("🤖 Hack Day Starter — Tool-Calling Agent");
  console.log(\`🎯 Model: \${MODEL_TAG} (Native Tool-Calling Verified)\`);
  console.log(\`🛠️  Active Tools: [\${TOOLS.map((t) => t.function.name).join(", ")}]\`);
  console.log(\`📡 Ollama Host: \${OLLAMA_HOST}\`);
  console.log("=================================================\\n");

  const client = new OllamaAgentClient(MODEL_TAG, OLLAMA_HOST);

  // 1. Verify connection to local Ollama daemon
  const isConnected = await client.checkConnection();
  if (!isConnected) {
    console.error("❌ ERROR: Could not connect to local Ollama at " + OLLAMA_HOST);
    console.error("\\nPlease ensure Ollama is installed and running:");
    console.error("  1. Start Ollama: 'ollama serve' (or open the desktop app)");
    console.error(\`  2. Pull the model: 'ollama pull \${MODEL_TAG}'\`);
    console.error("  3. Verify listener: curl http://localhost:11434/api/tags\\n");
    process.exit(1);
  }

  // 2. Verify model availability
  const isInstalled = await client.isModelInstalled();
  if (!isInstalled) {
    console.warn(\`⚠️ Notice: Model '\${MODEL_TAG}' was not found in your local Ollama library.\`);
    console.warn("Run the following command in another terminal tab to download it:");
    console.warn(\`  ollama pull \${MODEL_TAG}\\n\`);
  }

  console.log("✨ Agent ready! Try asking complex calculations or math problems:");
  console.log("Example: 'What is 342 multiplied by 19, and then divide by 4?'");
  console.log("Type 'exit' or press Ctrl+C to quit.\\n");

  const rl = createInterface({ input, output });
  const messages: ChatMessage[] = [
    { role: "system", content: SYSTEM_PROMPT },
  ];

  try {
    while (true) {
      let userInput: string;
      try {
        userInput = await rl.question("User: ");
      } catch {
        // Stream closed or EOF reached
        break;
      }
      const trimmed = userInput.trim();

      if (!trimmed) continue;
      if (trimmed.toLowerCase() === "exit" || trimmed.toLowerCase() === "quit") {
        console.log("Agent shutting down. Goodbye!");
        break;
      }

      messages.push({ role: "user", content: trimmed });

      // ---------------------------------------------------------------------
      // REAL TOOL-CALLING EXECUTION LOOP
      // ---------------------------------------------------------------------
      let loopCount = 0;
      const MAX_LOOPS = 5;

      while (loopCount < MAX_LOOPS) {
        loopCount++;
        console.log("Agent: Thinking...");

        const assistantMsg = await client.chatWithTools(messages, TOOLS);

        messages.push(assistantMsg);

        // Check if model emitted tool calls
        if (assistantMsg.tool_calls && assistantMsg.tool_calls.length > 0) {
          for (const toolCall of assistantMsg.tool_calls) {
            const funcName = toolCall.function.name;
            const args = toolCall.function.arguments;

            console.log(\`⚙️  [Tool Call] \${funcName}(\${JSON.stringify(args)})\`);

            const handler = TOOL_HANDLERS[funcName];
            let toolOutput: string;

            if (handler) {
              try {
                toolOutput = handler(args);
              } catch (e: any) {
                toolOutput = \`Execution error: \${e.message || e}\`;
              }
            } else {
              toolOutput = \`Error: Unknown tool '\${funcName}'\`;
            }

            console.log(\`📋 [Tool Result] \${toolOutput}\`);

            // Append tool response message to conversation history
            messages.push({
              role: "tool",
              content: toolOutput,
            });
          }

          // Continue loop so model synthesizes the tool result
          continue;
        }

        // If no more tool calls, output the final assistant response
        if (assistantMsg.content) {
          console.log(\`Agent: \${assistantMsg.content}\\n\`);
        }
        break;
      }
    }
  } finally {
    rl.close();
  }
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
`;

  return [
    { path: "README.md", content: readmeContent },
    { path: "package.json", content: packageJsonContent },
    { path: "tsconfig.json", content: tsconfigContent },
    { path: ".gitignore", content: gitignoreContent },
    { path: "src/tools/calculator.ts", content: calculatorToolContent },
    { path: "src/ollama.ts", content: ollamaClientContent },
    { path: "src/index.ts", content: indexContent },
  ];
}
