import { StarterFile, StarterGenerationOptions } from "../types";
import { formatModelDisplaySize } from "../../memory-calculator";
import { generateReadinessModule } from "./readiness";

export function generateChatStarter(options: StarterGenerationOptions): StarterFile[] {
  const { model, explanation } = options;
  const projectName = `hack-day-starter-chat-${model.family}`;
  const displaySize = formatModelDisplaySize(model);
  const contextK = (model.contextTokens / 1024).toFixed(0);

  const capabilitiesList = [
    model.capabilities.tools === true ? "Tools" : null,
    model.capabilities.vision === true ? "Vision" : null,
    model.capabilities.thinking === true ? "Thinking" : null,
  ]
    .filter(Boolean)
    .join(", ") || "General text";

  const whyThisModel =
    explanation ||
    `${model.displayName} was selected for its verified compatibility with your hardware and strong performance in general chat and reasoning tasks.`;

  // 1. README.md
  const readmeContent = `# ${projectName}

Generated by **Hack Day Starter**

A lightweight, zero-runtime-dependency TypeScript starter project for chatting with local Ollama models.

---

## Selected Model

- **Model:** ${model.displayName}
- **Provider:** ${model.provider}
- **Ollama tag:** \`${model.ollamaTag}\`
- **${model.exactManifestSizeBytes !== null ? "Manifest size" : "Ollama listed size"}:** ${displaySize}
- **Context Window:** ${contextK}k tokens (${model.contextTokens.toLocaleString()})
- **Quantization:** \`${model.quantization}\`
- **License:** ${model.license}
- **Capabilities:** ${capabilitiesList}
- **Primary Source:** [${model.ollamaUrl}](${model.ollamaUrl})

---

## Setup

Run the following commands in your terminal:

\`\`\`bash
# 1. Pull the verified model in Ollama
ollama pull ${model.ollamaTag}

# 2. Install project dev dependencies
npm install

# 3. Start the interactive chat
npm run dev
\`\`\`

---

## Why this model

${whyThisModel}

---

## How to change the model

You can point this starter project to any other local Ollama model in two ways:

1. **Using an environment variable** (no code changes):
   \`\`\`bash
   OLLAMA_MODEL="<other-model:tag>" npm run dev
   \`\`\`

2. **Or editing \`src/index.ts\`**:
   \`\`\`typescript
   const MODEL_TAG = process.env.OLLAMA_MODEL || "${model.ollamaTag}";
   \`\`\`

---

## Troubleshooting

- **Ollama connection error:** Make sure the Ollama daemon is running (\`ollama serve\` or launch the Ollama desktop application).
- **Model not found:** Run \`ollama pull ${model.ollamaTag}\` to download the model artifact.
- **Port conflicts:** If your Ollama server runs on a non-standard port, configure \`OLLAMA_HOST="http://localhost:11434" npm run dev\`.
`;

  // 2. package.json
  const packageJsonContent = JSON.stringify(
    {
      name: projectName,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        dev: "tsx src/index.ts",
        build: "tsc",
        start: "node dist/index.js",
      },
      devDependencies: {
        "@types/node": "^20.11.0",
        tsx: "^4.7.0",
        typescript: "^5.3.3",
      },
    },
    null,
    2
  ) + "\n";

  // 3. tsconfig.json
  const tsconfigContent = JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        esModuleInterop: true,
        strict: true,
        skipLibCheck: true,
        outDir: "./dist",
        rootDir: "./src",
      },
      include: ["src/**/*"],
    },
    null,
    2
  ) + "\n";

  // 4. .gitignore
  const gitignoreContent = `node_modules/
dist/
.env
.DS_Store
*.log
`;

  // 5. src/ollama.ts
  const ollamaClientContent = `/**
 * Direct client for local Ollama API.
 * Uses native Node.js fetch (no external SDK dependencies required).
 */

export interface ChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

export interface OllamaChatResponse {
  model: string;
  created_at: string;
  message: ChatMessage;
  done: boolean;
  total_duration?: number;
  load_duration?: number;
  prompt_eval_count?: number;
  eval_count?: number;
}

export class OllamaClient {
  private readonly baseUrl: string;
  public readonly modelTag: string;

  constructor(modelTag: string, baseUrl = "http://localhost:11434") {
    this.modelTag = modelTag;
    this.baseUrl = baseUrl.replace(/\\/$/, "");
  }

  /**
   * Sends a chat completion request to the local Ollama instance.
   */
  async chat(messages: ChatMessage[], systemPrompt?: string): Promise<string> {
    const payloadMessages: ChatMessage[] = [];
    if (systemPrompt) {
      payloadMessages.push({ role: "system", content: systemPrompt });
    }
    payloadMessages.push(...messages);

    const res = await fetch(\`\${this.baseUrl}/api/chat\`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: this.modelTag,
        messages: payloadMessages,
        stream: false,
      }),
    });

    if (!res.ok) {
      const errorText = await res.text().catch(() => res.statusText);
      throw new Error(\`Ollama API error (\${res.status}): \${errorText}\`);
    }

    const data = (await res.json()) as OllamaChatResponse;
    return data.message?.content || "";
  }
}
`;

  // 6. src/index.ts
  const indexContent = `import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { OllamaClient, ChatMessage } from "./ollama.js";
import { ensureOllamaReady } from "./readiness.js";

// Configured model tag: injected from Hack Day Starter recommendation
const MODEL_TAG = process.env.OLLAMA_MODEL || "${model.ollamaTag}";
const OLLAMA_HOST = process.env.OLLAMA_HOST || "http://localhost:11434";

async function main() {
  console.log("=================================================");
  console.log("🚀 Hack Day Starter — Local Chat");
  console.log(\`🤖 Model: \${MODEL_TAG}\`);
  console.log(\`📡 Ollama Host: \${OLLAMA_HOST}\`);
  console.log("=================================================\\n");

  const client = new OllamaClient(MODEL_TAG, OLLAMA_HOST);

  // Readiness check: Ollama reachable + exact model tag installed
  if (!(await ensureOllamaReady(OLLAMA_HOST, MODEL_TAG))) {
    process.exitCode = 1;
    return;
  }

  console.log("✨ Ready! Type your message and press Enter.");
  console.log("Type 'exit' or press Ctrl+C to quit.\\n");

  const rl = createInterface({ input, output });
  const history: ChatMessage[] = [];

  try {
    while (true) {
      let userInput: string;
      try {
        userInput = await rl.question("You: ");
      } catch {
        // Stream closed or reached EOF
        break;
      }
      const trimmed = userInput.trim();

      if (!trimmed) continue;
      if (trimmed.toLowerCase() === "exit" || trimmed.toLowerCase() === "quit") {
        console.log("Goodbye!");
        break;
      }

      history.push({ role: "user", content: trimmed });

      console.log("Assistant: Thinking...");
      try {
        const response = await client.chat(history);
        console.log(\`Assistant: \${response}\\n\`);
        history.push({ role: "assistant", content: response });
      } catch (err: any) {
        console.error(\`❌ Error from Ollama: \${err.message || err}\\n\`);
      }
    }
  } finally {
    rl.close();
  }
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
`;

  return [
    { path: "README.md", content: readmeContent },
    { path: "package.json", content: packageJsonContent },
    { path: "tsconfig.json", content: tsconfigContent },
    { path: ".gitignore", content: gitignoreContent },
    { path: "src/ollama.ts", content: ollamaClientContent },
    { path: "src/readiness.ts", content: generateReadinessModule() },
    { path: "src/index.ts", content: indexContent },
  ];
}
